In [3]:
import pandas as pd

excel_path = ("../data/raw/classification/Book1.xlsx")

#inspect the namnes without reading all data into memory
excel_file = pd.ExcelFile(excel_path)
print("Found Sheets:", excel_file.sheet_names)

Found Sheets: ['COMMUNICATION', 'CLEARANCE', 'AOsMEMOs', 'LEAVES']

In [4]:
header_rows = {
    "COMMUNICATION":2,
    "CLEARANCE": 0,
    "AOsMEMOs": 2,
    "LEAVES": 0,
}

for sheets in excel_file.sheet_names:
    header_row = header_rows.get(sheets,0)
    
    df = pd.read_excel(
        excel_file,
        sheet_name=sheets,
        header=header_row,

    )
    
    print(f"\n--- [{sheets}] ---")
    display(df)

--- [COMMUNICATION] ---

,DATE,CONTROL#,SUBJECT,DESCRIPTION,TYPE,OFFICE/PERSON FROM,OFFICE/UNIT CONCERNED,REMARKS,REMARKS 2,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,2024-01-02 00:00:00,2024-01-02-COM-OUT-01,REQUEST TO RENDER OVERTIME,REQUEST TO RENDER OVERTIME,OUT,ACCOUNTING,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-01-02 00:00:00,2024-01-02-COM-IN-01,PFC MEETING,"ADJUSTED RECEIPTS PROGRAM, SETTING OF POLICY, ...",IN,PROVINCIAL FINANCE COMMITTEE,"PROVINCIAL TREAS., ASST. PPDO AND PROVINCIAL A...",NaN,NaN,NaN,NaN,NaN
2,2024-01-02 00:00:00,2024-01-02-COM-IN-02,NOTICE OF ASSIGNMENT/ GRANT OF SECURITY INTEREST,CREDIT LINE AGREEMENT DATE 29 DECEMBER 2023,IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-03 00:00:00,2024-01-03-COM-IN-01,FY 2023 SUPPLEMENTAL BUDGET NO.02,FY 2023 SUPPLEMENTAL BUDGET NO.02,IN,DEPARTMENT OF BUDGET AND MANAGEMENT,HONORABLE MEMBERS OF THE SANGGUNIANG PANLALAWIGAN,NaN,NaN,NaN,NaN,NaN
4,2024-01-04 00:00:00,2024-01-04-COM-OUT-01,REQUEST FOR AN OPINION REGARDING THE INCLUSION...,REQUEST FOR AN OPINION REGARDING THE INCLUSION...,OUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2280,2026-09-22 00:00:00,2026-09-22-COM-OUT-02,REPLY TO LETTER RE: VOUCHERS OF C.J.T PASCUAL ...,REPLY TO LETTER RE: VOUCHERS OF C.J.T PASCUAL ...,OUT,ACCOUNTING,TREASURY,NaN,NaN,NaN,NaN,NaN
2281,2026-09-22 00:00:00,2026-09-22-COM-IN-05,COA DECISION NO. 2026-004,COA DECISION NO. 2026-004: REQUEST OF DR. CAYE...,IN,PRRU,ACCOUNTING,NaN,NaN,NaN,NaN,NaN
2282,2026-09-22 00:00:00,2026-09-22-COM-OUT-03,INDIVIDUAL PERFORMANCE COMMITMENT AND REVIEW (...,INDIVIDUAL PERFORMANCE COMMITMENT AND REVIEW (...,OUT,ACCOUNTING,HRMO,NaN,NaN,NaN,NaN,NaN
2283,2026-09-22 00:00:00,2026-09-22-COM-IN-06,NOTICE OF MEETING: CONSULTATIVE MEETING ON SEP...,NOTICE OF MEETING: CONSULTATIVE MEETING ON SEP...,IN,PEO,ACCOUNTING,MEETING,NaN,NaN,NaN,NaN
2284,2026-09-23 00:00:00,2026-09-23-COM-IN-01,SUBMISSION OF PROPOSED PROJECT FOR NTLB AGRICU...,SUBMISSION OF PROPOSED PROJECT FOR NTLB AGRICU...,IN,MUNICIPALITY OF STO. NIÑO,ACCOUNTING,NaN,NaN,NaN,NaN,NaN

--- [CLEARANCE] ---

,DATE,CONTROL#,FULL N AME,OFFICE,PURPOSE,REMARKS,RELEASING DATE,C/O,REMARKS 2,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,2024-11-20,2024-11-20-CLR-01,"ALAN, MARILYN T.",PEO,RETIREMENT,RELEASED,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-22,2024-11-22-CLR-01,"MATAMMU, MARIA PEACHINA B.",PHO,TRAVEL ABROAD,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-11-22,2024-11-22-CLR-02,"CARAG, ROGELIO",NaN,RETIREMENT,RELEASED,2024-11-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-11-25,2024-11-25-CLR-01,"BICCAN, CARIDAD",VET,RETIREMENT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-11-25,2024-11-25-CLR-02,"CALABUNG, AMELIA",VET,RETIREMENT,RELEASED,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,2026-09-15,2026-09-15-CLR-03,"DEL ROSARIO, GABBY O.",BALLESTEROS DISTRICT HOSPITAL,"RESIGNATION EFFECTIVE FEBRUARY 26, 2026",RELEASED,2026-09-17,LEOVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
698,2026-09-15,2026-09-15-CLR-04,"DORANO, KRISHA S.",BALLESTEROS DISTRICT HOSPITAL,"MATERNITY LEAVE EFFECTIVE OCTOBER 30, 2026",RELEASED,2026-09-17,LEOVER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,2026-09-15,2026-09-15-CLR-05,"LIONGSON, DEVON REY S.",NUESTRA SEÑORA DE PIAT DISTRICT HOSPITAL,TRAVEL ABROAD (VIETNAM) SEPTEMBER 30 TO OCTOBE...,RELEASED,2026-09-15,MA'AM NERISSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
700,2026-09-17,2026-09-17-CLR-01,"GILBUENA, PALOMA S.",GOVERNOR'S OFFICE,"TRAVEL ABROAD (THAILAND) OCTOBER 1-4, 2026",RELEASED,2026-09-17,SIR JAYSON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
701,2026-09-18,2026-09-18-CLR-01,"VENTOLERO, ED ARMAND T.",SANGGUNIANG PANLALAWIGAN OFFICE,"TRAVEL ABROAD ( SINGAPORE) DECEMBER 20 - 29, 2026",RELEASED,2026-09-18,SIR RONNIE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- [AOsMEMOs] ---

,DATE RECEIVED,DOCUMENT DATE,AO/MEMO/EO #,SUBJECT,OFFICE/UNIT/PERSON FROM,REMARKS
0,2026-01-26,2026-01-23,EO-2026-01,EXECUTIVE ORDER NO. 01 - STREAMLINING AND RATI...,GO,2026-01-26-COM-IN-04
1,2026-01-29,2026-01-28,AO-2026-02,ORDER ADOPTING THE GUIDELINES ON THE USE AND O...,GO,2026-01-29-COM-IN-01
2,2026-02-05,2026-01-21,AO-2026-1A,APPROVING AND ADOPTING THE JOINT RESOLUTION NO...,GO,2026-02-05-COM-IN-05
3,2026-02-05,2026-02-05,AO-2026-03,SUPPLEMENTAL ADMINISTRATIVE ORDER STRENGTHENIN...,GO,2026-02-05-COM-IN-10
4,2026-02-16,2026-02-13,EO-2026-06,RECONSTITUTING THE COMPREHENSIVE DEVELOPMENT P...,GO,2026-02-16-COM-IN-03
5,2026-03-13,2026-02-23,AO-2026-09,INSTITUTING THE STANDARD RATES FOR MEALS AND S...,PA,2026-03-13-COM-IN-01
6,2026-03-13,2026-03-13,EO-2026-11,AN EXECUTIVE ORDER ADOPTING ENERGY CONSERVATIO...,PA,2026-03-13-COM-IN-02
7,2026-03-17,2026-03-17,AO-2026-10,"AN ORDER PRESCRIBING COMPREHENSIVE POLICIES, G...",GO,2026-03-17-COM-IN-03
8,2026-03-30,2026-03-19,MEMO-2026-34A,MEMORANDUM 34A: REQUEST FOR PERMANENT ALTERNAT...,GO,NaN
9,2026-04-13,2026-04-13,MEMO-2026-04-13-01,DOCUMENTARY REQUIREMENTS FOR REIMBURSEMENT OF ...,ACCOUNTING,NaN
10,2026-04-14,2026-04-06,MEMO-2026-41C,DIRECTIVE ON MANDATORY COMPLIANCE WITH REPUBLI...,GO,NaN
11,2026-04-14,2026-04-06,MEMO-2026-41,REITERATE THE SUBMISSION OF THE PPA FOR POSSIB...,GO,NaN
12,2026-04-27,2026-04-22,MEMO-2026-28,MEMORANDUM ORDER NO. 28 S. 2026 ADOPTION OF LA...,PA,NaN
13,2026-05-11,2026-05-11,AO-2026-13,REORGANIZING THE ADMINISTRATIVE AND FINANCIAL ...,GO,NaN

--- [LEAVES] ---

,DATE FILED,TRANSMITAL DATE,CONTROL#,NAME,TYPE OF LEAVE,REMARKS,DAY/S APPLIED,DATE RECEIVED,STATUS
0,2024-10-28,NaT,2024-10-28-LEAVE-IN-01,"GARMA,JEANNA C.",SPECIAL PRIVILEGE,BIRTHDAY,NaN,2024-10-29,APPROVED
1,2024-11-01,NaT,2024-11-01-LEAVE-01,"URSULUM,MARELLA PEARL",VACATION LEAVE,TRAVEL ABROAD,NaN,2024-11-12,APPROVED
2,2024-11-01,NaT,2024-11-01-LEAVE-02,"URSULUM,MARELLA PEARL",MANDATORY,TRAVEL ABROAD,NaN,2024-11-12,APPROVED
3,2024-11-05,NaT,2024-11-05-LEAVE-IN-01,"DELA CRUZ, JOLIE M.",SPECIAL PRIVILEGE,TO ATTEND PERSONAL MATTER,NaN,2024-11-05,APPROVED
4,2024-11-12,NaT,2024-11-12-LEAVE-IN-01,"GERVACIO, JENNIFER D.",SPECIAL PRIVILEGE,TO ATTEND PERSONAL MATTER,NaN,2024-11-12,APPROVED
...,...,...,...,...,...,...,...,...,...
652,2026-09-21,2026-09-21,2026-09-21-LEAVE-02,"ABAD, ALYZA L.",WELLNESS LEAVE,NaN,"SEPTEMBER 25 & 28, 2026",NaT,NaN
653,2026-09-21,2026-09-21,2026-09-21-LEAVE-03,"URSULUM, MARELLA PEARL JOIE",SICK LEAVE,NaN,"SEPTEMBER 18,2026",NaT,NaN
654,2026-09-22,2026-09-22,2026-09-22-LEAVE-01,"PEREZ, BENEDICT S.",SICK LEAVE,NaN,"SEPTEMBER 21, 2026",NaT,NaN
655,2026-09-22,2026-09-22,2026-09-22-LEAVE-02,"GARMA, JEANNA C.",WELLNESS LEAVE,NaN,"SEPTEMBER 6 & 7, 2026",NaT,NaN
656,2026-09-23,2026-09-23,2026-09-23-LEAVE-01,"CORPUZ, CRISEL S.",SICK LEAVE,NaN,"SEPTEMBER 22, 2026",NaT,NaN

In [5]:
print(df.shape) #dimensionality: (rows, columns)
print(df.columns.tolist()) #schema / feature names
print(df.dtypes) #data types inferred by pandas
print(df.isna().sum()) #missing-value detection
print(df.duplicated().sum()) #check duplicate records

(657, 9)
['DATE FILED', 'TRANSMITAL DATE', 'CONTROL#', 'NAME', 'TYPE OF LEAVE', 'REMARKS', 'DAY/S APPLIED', 'DATE RECEIVED', 'STATUS']
DATE FILED         datetime64[us]
TRANSMITAL DATE    datetime64[us]
CONTROL#                      str
NAME                          str
TYPE OF LEAVE                 str
REMARKS                       str
DAY/S APPLIED                 str
DATE RECEIVED      datetime64[us]
STATUS                        str
dtype: object
DATE FILED           6
TRANSMITAL DATE     44
CONTROL#             4
NAME                 4
TYPE OF LEAVE        5
REMARKS            616
DAY/S APPLIED       45
DATE RECEIVED       45
STATUS              38
dtype: int64
3

In [6]:
print(f"\n---{sheets}---")
print("Shape", df.shape)
print("Duplicates:", df.duplicated().sum())
print("\nMissing values:")
print(df.isna().sum())

---LEAVES---
Shape (657, 9)
Duplicates: 3

Missing values:
DATE FILED           6
TRANSMITAL DATE     44
CONTROL#             4
NAME                 4
TYPE OF LEAVE        5
REMARKS            616
DAY/S APPLIED       45
DATE RECEIVED       45
STATUS              38
dtype: int64

In [7]:
#investigate the 3 duplicates 
duplicates = df[df.duplicated(keep=False)]
display(duplicates)

,DATE FILED,TRANSMITAL DATE,CONTROL#,NAME,TYPE OF LEAVE,REMARKS,DAY/S APPLIED,DATE RECEIVED,STATUS
209,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
234,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
393,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
429,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [8]:
#detect empty rows
empty_rows  = df[df.isna().all(axis=1)]
display(empty_rows)

,DATE FILED,TRANSMITAL DATE,CONTROL#,NAME,TYPE OF LEAVE,REMARKS,DAY/S APPLIED,DATE RECEIVED,STATUS
209,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
234,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
393,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN
429,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [9]:
#how="all" means : drop a row only when every column is Null
df = df.dropna(how="all")

In [10]:
#inspect categorical columns
print(df["TYPE OF LEAVE"].value_counts(dropna=False))
print(df["STATUS"].value_counts(dropna=False))

TYPE OF LEAVE
SICK LEAVE                203
COMPENSATORY              132
SPL                       109
MANDATORY                  85
WELLNESS LEAVE             49
MONETIZATION               27
VACATION LEAVE             19
SPECIAL PRIVILEGE           5
MANDATORY LEAVE             4
COC                         4
SPECIAL EMERGENCY           2
MANDATORY/FORCED LEAVE      2
LEAVE WITHOUT PAY           2
STUDY LEAVE                 1
NaN                         1
TERMINAL                    1
SICK LEAVE\nPATERNITY       1
SICK LEAVE                  1
MATERNITY                   1
MANDATORY & SPL             1
PATERNITY LEAVE             1
MANDATORY                   1
FORCED LEAVE                1
Name: count, dtype: int64
STATUS
APPROVED       614
NaN             34
CANCELLED        4
DISAPPROVED      1
Name: count, dtype: int64

In [11]:
df["TYPE OF LEAVE"] = (
    df["TYPE OF LEAVE"]
    .str.strip()
    .str.upper()
)

#You should see some categories merge.
df["TYPE OF LEAVE"].value_counts(dropna=False)

TYPE OF LEAVE
SICK LEAVE                204
COMPENSATORY              132
SPL                       109
MANDATORY                  86
WELLNESS LEAVE             49
MONETIZATION               27
VACATION LEAVE             19
SPECIAL PRIVILEGE           5
MANDATORY LEAVE             4
COC                         4
SPECIAL EMERGENCY           2
MANDATORY/FORCED LEAVE      2
LEAVE WITHOUT PAY           2
STUDY LEAVE                 1
NaN                         1
TERMINAL                    1
SICK LEAVE\nPATERNITY       1
MATERNITY                   1
MANDATORY & SPL             1
PATERNITY LEAVE             1
FORCED LEAVE                1
Name: count, dtype: int64

In [12]:
#for clearance and AOsMEMOs, inspect the raw rows again
for sheet in ["CLEARANCE", "AOsMEMOs"]:
    sample =pd.read_excel(
        excel_path, sheet_name=sheets,
        header=None, nrows=8
    )
    display(sample)

,0,1,2,3,4,5,6,7,8
0,DATE FILED,TRANSMITAL DATE,CONTROL#,NAME,TYPE OF LEAVE,REMARKS,DAY/S APPLIED,DATE RECEIVED,STATUS
1,2024-10-28 00:00:00,NaN,2024-10-28-LEAVE-IN-01,"GARMA,JEANNA C.",SPECIAL PRIVILEGE,BIRTHDAY,NaN,2024-10-29 00:00:00,APPROVED
2,2024-11-01 00:00:00,NaN,2024-11-01-LEAVE-01,"URSULUM,MARELLA PEARL",VACATION LEAVE,TRAVEL ABROAD,NaN,2024-11-12 00:00:00,APPROVED
3,2024-11-01 00:00:00,NaN,2024-11-01-LEAVE-02,"URSULUM,MARELLA PEARL",MANDATORY,TRAVEL ABROAD,NaN,2024-11-12 00:00:00,APPROVED
4,2024-11-05 00:00:00,NaN,2024-11-05-LEAVE-IN-01,"DELA CRUZ, JOLIE M.",SPECIAL PRIVILEGE,TO ATTEND PERSONAL MATTER,NaN,2024-11-05 00:00:00,APPROVED
5,2024-11-12 00:00:00,NaN,2024-11-12-LEAVE-IN-01,"GERVACIO, JENNIFER D.",SPECIAL PRIVILEGE,TO ATTEND PERSONAL MATTER,NaN,2024-11-12 00:00:00,APPROVED
6,2024-11-18 00:00:00,NaN,2024-11-18-LEAVE-IN-01,"VILORIA, YVES L.",SICK LEAVE,COUGH AND COLD,NaN,2025-01-06 00:00:00,APPROVED
7,2024-11-21 00:00:00,NaN,2024-11-21-LEAVE-IN-01,"CAFIRMA, DIANA R.",SICK LEAVE,HEADACHE,NaN,2024-11-21 00:00:00,APPROVED

,0,1,2,3,4,5,6,7,8
0,DATE FILED,TRANSMITAL DATE,CONTROL#,NAME,TYPE OF LEAVE,REMARKS,DAY/S APPLIED,DATE RECEIVED,STATUS
1,2024-10-28 00:00:00,NaN,2024-10-28-LEAVE-IN-01,"GARMA,JEANNA C.",SPECIAL PRIVILEGE,BIRTHDAY,NaN,2024-10-29 00:00:00,APPROVED
2,2024-11-01 00:00:00,NaN,2024-11-01-LEAVE-01,"URSULUM,MARELLA PEARL",VACATION LEAVE,TRAVEL ABROAD,NaN,2024-11-12 00:00:00,APPROVED
3,2024-11-01 00:00:00,NaN,2024-11-01-LEAVE-02,"URSULUM,MARELLA PEARL",MANDATORY,TRAVEL ABROAD,NaN,2024-11-12 00:00:00,APPROVED
4,2024-11-05 00:00:00,NaN,2024-11-05-LEAVE-IN-01,"DELA CRUZ, JOLIE M.",SPECIAL PRIVILEGE,TO ATTEND PERSONAL MATTER,NaN,2024-11-05 00:00:00,APPROVED
5,2024-11-12 00:00:00,NaN,2024-11-12-LEAVE-IN-01,"GERVACIO, JENNIFER D.",SPECIAL PRIVILEGE,TO ATTEND PERSONAL MATTER,NaN,2024-11-12 00:00:00,APPROVED
6,2024-11-18 00:00:00,NaN,2024-11-18-LEAVE-IN-01,"VILORIA, YVES L.",SICK LEAVE,COUGH AND COLD,NaN,2025-01-06 00:00:00,APPROVED
7,2024-11-21 00:00:00,NaN,2024-11-21-LEAVE-IN-01,"CAFIRMA, DIANA R.",SICK LEAVE,HEADACHE,NaN,2024-11-21 00:00:00,APPROVED

In [13]:
#X: information describing the document
#Y: document type

dataframes = {}
#dataframes is a dictionary of DataFrames. Each sheet name becomes a key.


for sheet in ["CLEARANCE", "AOsMEMOs"]:
    sample = pd.read_excel(
        excel_path,
        sheet_name=sheet,
        # nrows=8,
        header=header_rows.get(sheet, 0)
    )
    dataframes[sheet] = sample
    # display(sample)


#Inspect only the schema
for sheet, df in dataframes.items():
    print(f"\n{sheet}")
    print(df.shape)
    print(df.columns.tolist())
    display(df.head(2))

CLEARANCE
(702, 16)
['DATE', 'CONTROL#', 'FULL N AME', 'OFFICE', 'PURPOSE', 'REMARKS', 'RELEASING DATE', 'C/O', 'REMARKS 2', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15']

,DATE,CONTROL#,FULL N AME,OFFICE,PURPOSE,REMARKS,RELEASING DATE,C/O,REMARKS 2,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,2024-11-20,2024-11-20-CLR-01,"ALAN, MARILYN T.",PEO,RETIREMENT,RELEASED,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-22,2024-11-22-CLR-01,"MATAMMU, MARIA PEACHINA B.",PHO,TRAVEL ABROAD,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

AOsMEMOs
(14, 6)
['DATE RECEIVED', 'DOCUMENT DATE', 'AO/MEMO/EO #', 'SUBJECT', 'OFFICE/UNIT/PERSON FROM', 'REMARKS']

,DATE RECEIVED,DOCUMENT DATE,AO/MEMO/EO #,SUBJECT,OFFICE/UNIT/PERSON FROM,REMARKS
0,2026-01-26,2026-01-23,EO-2026-01,EXECUTIVE ORDER NO. 01 - STREAMLINING AND RATI...,GO,2026-01-26-COM-IN-04
1,2026-01-29,2026-01-28,AO-2026-02,ORDER ADOPTING THE GUIDELINES ON THE USE AND O...,GO,2026-01-29-COM-IN-01

In [14]:
#check for null value columns here
for column in dataframes["CLEARANCE"].columns:
    print(column, dataframes["CLEARANCE"][column].isna().all())

DATE False
CONTROL# False
FULL N AME False
OFFICE False
PURPOSE False
REMARKS False
RELEASING DATE False
C/O False
REMARKS 2 False
Unnamed: 9 True
Unnamed: 10 True
Unnamed: 11 True
Unnamed: 12 True
Unnamed: 13 True
Unnamed: 14 True
Unnamed: 15 False

In [15]:

#checking the not null value of Unnamed 15 since at top result it is False
col = "Unnamed: 15"

print("Non-null count:", dataframes["CLEARANCE"][col].notna().sum())
display(
    dataframes["CLEARANCE"][
        dataframes["CLEARANCE"][col].notna()
    ]
)

Non-null count: 1

,DATE,CONTROL#,FULL N AME,OFFICE,PURPOSE,REMARKS,RELEASING DATE,C/O,REMARKS 2,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
272,2025-07-22,2025-07-22-CLR-02,"TORRES, MADELYN M.",MATILDE A. OLIVAS DISTRICT HOSPITAL,SICK LEAVE,RELEASED,2025-07-22,MADELYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [16]:
df = dataframes["CLEARANCE"]

unnamed_cols = [
    col for col in df.columns
    if col.startswith("Unnamed")
]

#drop the null columns
df = df.drop(columns=unnamed_cols)
dataframes["CLEARANCE"] =df

In [17]:
#then verify
#for clearances
print(dataframes["CLEARANCE"].shape)
print(dataframes["CLEARANCE"].columns.tolist())


#for AOsMEMOs
print(dataframes["AOsMEMOs"].shape)
print(dataframes["AOsMEMOs"].columns.tolist())

#Correct headers - checked
#Remove junk columns - checked

(702, 9)
['DATE', 'CONTROL#', 'FULL N AME', 'OFFICE', 'PURPOSE', 'REMARKS', 'RELEASING DATE', 'C/O', 'REMARKS 2']
(14, 6)
['DATE RECEIVED', 'DOCUMENT DATE', 'AO/MEMO/EO #', 'SUBJECT', 'OFFICE/UNIT/PERSON FROM', 'REMARKS']

In [18]:
#profile all classes
for sheet, df in dataframes.items():
    print(f"\n--- {sheet} ---")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Duplicates:", df.duplicated().sum())
    print("Missing values:")
    print(df.isna().sum())

--- CLEARANCE ---
Rows: 702
Columns: 9
Duplicates: 0
Missing values:
DATE                0
CONTROL#            0
FULL N AME          0
OFFICE             12
PURPOSE             9
REMARKS            23
RELEASING DATE     24
C/O                40
REMARKS 2         696
dtype: int64

--- AOsMEMOs ---
Rows: 14
Columns: 6
Duplicates: 0
Missing values:
DATE RECEIVED              0
DOCUMENT DATE              0
AO/MEMO/EO #               0
SUBJECT                    0
OFFICE/UNIT/PERSON FROM    0
REMARKS                    6
dtype: int64

In [19]:
#FEATURE SELECTION
dataframes = {}

for sheet in excel_file.sheet_names: #the list of worksheet names.
    df = pd.read_excel(
        excel_file,
        sheet_name=sheet,
        header=header_rows.get(sheet, 0)
    )

    dataframes[sheet] = df #dictionary assignment.

In [20]:
for sheet, df in dataframes.items():
    df = df.dropna(how="all") #how="all" means: only remove a row if every column in that row is null
    dataframes[sheet] =df

In [21]:
for sheet, df in dataframes.items():
    df = df.dropna(axis=1, how="all")
    dataframes[sheet] = df

In [22]:
for sheet, df in dataframes.items():
    print(f"\n---{sheet}---")
    print("Rows: ", len(df))
    print("Columns", len(df.columns))
    print("duplicates:", df.duplicated().sum())
    print("Null Columns:\n", df.isna().sum(0))
    print("Column names:", df.columns.tolist())

---COMMUNICATION---
Rows:  2285
Columns 11
duplicates: 0
Null Columns:
 DATE                        2
CONTROL#                    0
SUBJECT                     0
DESCRIPTION                 0
TYPE                        0
OFFICE/PERSON FROM         67
OFFICE/UNIT CONCERNED     170
REMARKS                  1576
REMARKS 2                2240
Unnamed: 10              2282
Unnamed: 11              2282
dtype: int64
Column names: ['DATE', 'CONTROL#', 'SUBJECT', 'DESCRIPTION', 'TYPE', 'OFFICE/PERSON FROM', 'OFFICE/UNIT CONCERNED', 'REMARKS', 'REMARKS 2', 'Unnamed: 10', 'Unnamed: 11']

---CLEARANCE---
Rows:  702
Columns 10
duplicates: 0
Null Columns:
 DATE                0
CONTROL#            0
FULL N AME          0
OFFICE             12
PURPOSE             9
REMARKS            23
RELEASING DATE     24
C/O                40
REMARKS 2         696
Unnamed: 15       701
dtype: int64
Column names: ['DATE', 'CONTROL#', 'FULL N AME', 'OFFICE', 'PURPOSE', 'REMARKS', 'RELEASING DATE', 'C/O', 'REMARKS 2', 'Unnamed: 15']

---AOsMEMOs---
Rows:  14
Columns 6
duplicates: 0
Null Columns:
 DATE RECEIVED              0
DOCUMENT DATE              0
AO/MEMO/EO #               0
SUBJECT                    0
OFFICE/UNIT/PERSON FROM    0
REMARKS                    6
dtype: int64
Column names: ['DATE RECEIVED', 'DOCUMENT DATE', 'AO/MEMO/EO #', 'SUBJECT', 'OFFICE/UNIT/PERSON FROM', 'REMARKS']

---LEAVES---
Rows:  653
Columns 9
duplicates: 0
Null Columns:
 DATE FILED           2
TRANSMITAL DATE     40
CONTROL#             0
NAME                 0
TYPE OF LEAVE        1
REMARKS            612
DAY/S APPLIED       41
DATE RECEIVED       41
STATUS              34
dtype: int64
Column names: ['DATE FILED', 'TRANSMITAL DATE', 'CONTROL#', 'NAME', 'TYPE OF LEAVE', 'REMARKS', 'DAY/S APPLIED', 'DATE RECEIVED', 'STATUS']

C:\Users\ASUS\AppData\Local\Temp\ipykernel_25148\696814466.py:6: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  print("Null Columns:\n", df.isna().sum(0))

In [23]:
#will remove all the columns with Unnamed label
for sheet, df in dataframes.items():
    unnamed = [
        col for col in df.columns
        if str(col).startswith("Unnamed")
    ]

    dataframes[sheet] = df.drop(columns=unnamed)

In [24]:
comm = dataframes["COMMUNICATION"]
comm["label"] = "COMMUNICATION"

#communication
comm["document_text"] = (
    comm["SUBJECT"].fillna("") + " " +
    comm["DESCRIPTION"].fillna("") + " " +
    comm["TYPE"].fillna("") + " " +
    comm["OFFICE/PERSON FROM"].fillna("")
    
)


#clearance
clea =dataframes["CLEARANCE"]
clea["label"] = "CLEARANCE"

clea["document_text"] = (
    clea["OFFICE"].fillna("") + " " +
    clea["PURPOSE"].fillna("") + " " +
    clea["C/O"].fillna("") + " " +
    clea["REMARKS"].fillna("")
)


#AOsMEMOs
ao_memo = dataframes["AOsMEMOs"]
ao_memo["label"] = "AOsMEMOs"

ao_memo["document_text"] =(
ao_memo["AO/MEMO/EO #"].fillna("") + " " + 
ao_memo["SUBJECT"].fillna("") + " " +
ao_memo["OFFICE/UNIT/PERSON FROM"].fillna("") + " " +
ao_memo["REMARKS"].fillna("")
)

#LEAVE
leave = dataframes["LEAVES"]
leave["label"] = "LEAVES"

leave["document_text"] = (
    leave["TYPE OF LEAVE"].fillna("") + " " +
    leave["DAY/S APPLIED"].fillna("") + " " +
    leave["REMARKS"].fillna("")
)




#fillna("") is missing-value imputation. Here we're replacing missing text with an empty string.
#+ " " + is string concatenation.
#document_text becomes your engineered input feature.
#labeling the data

#then inspect
display(comm[["document_text", "label"]].head())
display(clea[["document_text", "label"]].head())
display(ao_memo[["document_text", "label"]].head())
display(leave[["document_text", "label"]].head())

                                       document_text          label
0  REQUEST  TO RENDER OVERTIME REQUEST  TO RENDER...  COMMUNICATION
1  PFC MEETING ADJUSTED RECEIPTS PROGRAM, SETTING...  COMMUNICATION
2  NOTICE OF ASSIGNMENT/ GRANT OF SECURITY INTERE...  COMMUNICATION
3  FY 2023 SUPPLEMENTAL BUDGET NO.02 FY 2023 SUPP...  COMMUNICATION
4  REQUEST FOR AN OPINION REGARDING THE INCLUSION...  COMMUNICATION

              document_text      label
0  PEO RETIREMENT  RELEASED  CLEARANCE
1       PHO TRAVEL ABROAD    CLEARANCE
2      RETIREMENT  RELEASED  CLEARANCE
3          VET RETIREMENT    CLEARANCE
4  VET RETIREMENT  RELEASED  CLEARANCE

                                       document_text     label
0  EO-2026-01 EXECUTIVE ORDER NO. 01 - STREAMLINI...  AOsMEMOs
1  AO-2026-02 ORDER ADOPTING THE GUIDELINES ON TH...  AOsMEMOs
2  AO-2026-1A APPROVING AND ADOPTING THE JOINT RE...  AOsMEMOs
3  AO-2026-03 SUPPLEMENTAL ADMINISTRATIVE ORDER S...  AOsMEMOs
4  EO-2026-06 RECONSTITUTING THE COMPREHENSIVE DE...  AOsMEMOs

                                  document_text   label
0                   SPECIAL PRIVILEGE  BIRTHDAY  LEAVES
1                 VACATION LEAVE  TRAVEL ABROAD  LEAVES
2                      MANDATORY  TRAVEL ABROAD  LEAVES
3  SPECIAL PRIVILEGE  TO ATTEND PERSONAL MATTER  LEAVES
4  SPECIAL PRIVILEGE  TO ATTEND PERSONAL MATTER  LEAVES

In [25]:
dataset = pd.concat([
    comm[["document_text", "label"]],
    clea[["document_text", "label"]],
    ao_memo[["document_text", "label"]],
    leave[["document_text", "label"]],
], ignore_index=True)

#inspect
print(dataset.shape)
print(dataset["label"].value_counts())
print(dataset.head(5))
print(dataset.tail(5))

(3654, 2)
label
COMMUNICATION    2285
CLEARANCE         702
LEAVES            653
AOsMEMOs           14
Name: count, dtype: int64
                                       document_text          label
0  REQUEST  TO RENDER OVERTIME REQUEST  TO RENDER...  COMMUNICATION
1  PFC MEETING ADJUSTED RECEIPTS PROGRAM, SETTING...  COMMUNICATION
2  NOTICE OF ASSIGNMENT/ GRANT OF SECURITY INTERE...  COMMUNICATION
3  FY 2023 SUPPLEMENTAL BUDGET NO.02 FY 2023 SUPP...  COMMUNICATION
4  REQUEST FOR AN OPINION REGARDING THE INCLUSION...  COMMUNICATION
                                document_text   label
3649  WELLNESS LEAVE SEPTEMBER 25 & 28, 2026   LEAVES
3650            SICK LEAVE SEPTEMBER 18,2026   LEAVES
3651           SICK LEAVE SEPTEMBER 21, 2026   LEAVES
3652    WELLNESS LEAVE SEPTEMBER 6 & 7, 2026   LEAVES
3653           SICK LEAVE SEPTEMBER 22, 2026   LEAVES

In [26]:
#next important check is whether any document_text became blank or nearly blank.
blank=dataset["document_text"].str.strip().eq("")
print("Blank document_text:", blank.sum())

Blank document_text: 4

In [27]:
#inspect those 5 blank rows
blank_rows =dataset[
    dataset["document_text"].str.strip().eq("") #eq = element wise equality test
]

display(blank_rows)

#so we will remove these 5 rows that are not usable
dataset = dataset[
    dataset["document_text"].str.strip().ne("") #ne means not equal to empty string

].copy() # copy() creates a new independent DataFram and helps avoid pandas views/assignments issues later

     document_text      label
2292                CLEARANCE
2296                CLEARANCE
2304                CLEARANCE
2305                CLEARANCE

In [28]:
blank_clearance = clea[
    clea["document_text"].str.strip().eq("")
]

blank_leaves = leave[
    leave["document_text"].str.strip().eq("")
]


# display(blank_clearance)
# display(blank_leaves)


display(
    blank_clearance[
        ["FULL N AME", "OFFICE", "PURPOSE", "REMARKS", "C/O", "REMARKS 2"]
    ]
)

display(
    blank_leaves[
        ["NAME", "TYPE OF LEAVE", "REMARKS", "DAY/S APPLIED", "STATUS"]
    ]
)

#If the rows have no useful semantic content, remove those blanks
# dataset=dataset[
#     dataset["document_text"].str.strip().ne("")

# ].copy()

               FULL N AME OFFICE PURPOSE REMARKS  C/O REMARKS 2
7   SIBAL, KRISHA MARIE D    NaN     NaN     NaN  NaN       NaN
11     MALANA, MAILILY C.    NaN     NaN     NaN  NaN       NaN
19   DECANO,DAN ALVARO C.    NaN     NaN     NaN  NaN       NaN
20   QUILANG,JACKIELOU T.    NaN     NaN     NaN  NaN       NaN

Empty DataFrame
Columns: [NAME, TYPE OF LEAVE, REMARKS, DAY/S APPLIED, STATUS]
Index: []

In [29]:
print(dataset["label"].value_counts())

print("Duplicate document_text:",
      dataset["document_text"].duplicated().sum()
      )

duplicate_texts = dataset[
    dataset["document_text"].duplicated(keep=False)
]

display(duplicate_texts.sort_values("document_text").head(20))

label
COMMUNICATION    2285
CLEARANCE         698
LEAVES            653
AOsMEMOs           14
Name: count, dtype: int64
Duplicate document_text: 359

                                          document_text          label
2308                                           RELEASED      CLEARANCE
2294                                           RELEASED      CLEARANCE
2295                                           RELEASED      CLEARANCE
2300                                           RELEASED      CLEARANCE
2303                               RETIREMENT  RELEASED      CLEARANCE
2287                               RETIREMENT  RELEASED      CLEARANCE
2290                               RETIREMENT  RELEASED      CLEARANCE
2622  ALCALA MUNICIPAL HOSPITAL TRAVEL ABROAD KAREN ...      CLEARANCE
2778  ALCALA MUNICIPAL HOSPITAL TRAVEL ABROAD KAREN ...      CLEARANCE
517   AOM NO. 2025-010:  AOM NO. 2025-010: AUDIT OBS...  COMMUNICATION
506   AOM NO. 2025-010:  AOM NO. 2025-010: AUDIT OBS...  COMMUNICATION
2667  APARRI PROVINCIAL HOSPITAL MATERNITY LEAVE CLA...      CLEARANCE
2682  APARRI PROVINCIAL HOSPITAL MATERNITY LEAVE CLA...      CLEARANCE
2416  APARRI PROVINCIAL HOSPITAL SICK LEAVE CLAIRE R...      CLEARANCE
2586  APARRI PROVINCIAL HOSPITAL SICK LEAVE CLAIRE R...      CLEARANCE
2560  APARRI PROVINCIAL HOSPITAL TRAVEL ABROAD CLAIR...      CLEARANCE
2544  APARRI PROVINCIAL HOSPITAL TRAVEL ABROAD CLAIR...      CLEARANCE
2340           APEMDH TRAVEL ABROAD GIAN SURIO RELEASED      CLEARANCE
2352           APEMDH TRAVEL ABROAD GIAN SURIO RELEASED      CLEARANCE
2523              APEMDH TRAVEL ABROAD LETICIA RELEASED      CLEARANCE

In [30]:
#But don’t delete the 359 yet. The next step is to determine whether they are:
# true duplicate records, or
# legitimate different records that still happen to produce identical text.
for label, group in dataset.groupby("label"):
    dupes = group["document_text"].duplicated().sum()
    print(label, dupes)

    print(
        dataset["document_text"]
        .value_counts()
        .head(20)

    )

#purpose of this is to avoid that may be a feature collision, not a duplicate record.

AOsMEMOs 0
document_text
SP TRAVEL ABROAD JC RELEASED                                                                                                                                                                                                                        18
MONETIZATION 10 DAYS                                                                                                                                                                                                                                16
SP TERMINAL  JC RELEASED                                                                                                                                                                                                                            14
BM TRAVEL ABROAD GENEVIVE RELEASED                                                                                                                                                                                                                  13
GO TRANSITION FOR THE NEW ADMINISTRATION MARK BALLAD RELEASED                                                                                                                                                                                       11
SP TERMINAL  JB RELEASED                                                                                                                                                                                                                             9
REVIEW DETAILS AND MAKE ACTIONS NECESSARY TO COMPLY WITH THE RECOMMENDATION. ATTACHMENT : AOM NO. 2023-006(2025) REVIEW DETAILS AND MAKE ACTIONS NECESSARY TO COMPLY WITH THE RECOMMENDATION. ATTACHMENT : AOM NO. 2023-006(2025) OUT ACCOUNTING     8
VGO TERMINAL  JC RELEASED                                                                                                                                                                                                                            8
SP TRAVEL ABROAD GENEVIVE RELEASED                                                                                                                                                                                                                   8
VICE GOVERNOR TERMINAL  JC RELEASED                                                                                                                                                                                                                  6
PEO RETIREMENT JAYSON RELEASED                                                                                                                                                                                                                       6
PROV'L OFFICE FOR PEOPLE EMPOWERMENT TRAVEL ABROAD (THAILAND) OCTOBER 1 - 4, 2026 SIR MATEO RELEASED                                                                                                                                                 6
GO TERMINAL  MARK BALLAD RELEASED                                                                                                                                                                                                                    5
CHECK TRANSACTION SLIP CHECK TRANSACTION SLIP IN BUREAU OF INTERNAL REVENUE                                                                                                                                                                          4
   RELEASED                                                                                                                                                                                                                                          4
OPA RETIREMENT LOIDA RELEASED                                                                                                                                                                                                                        4
SP TRAVEL ABROAD RONIE RELEASED                                                                                                                                                                                                                      4
BOARD MEMBER TRAVEL ABROAD JOY RELEASED                                                                                                                                                                                                              4
PROVINCIAL NATURAL RESOURCES AND ENVIRONMENTAL OFFICE TERMINAL PAY EFFECTIVE JANUARY 1, 2026) C/O BIANCA RELEASED                                                                                                                                    4
SICK LEAVE  BODY PAIN                                                                                                                                                                                                                                4
Name: count, dtype: int64
CLEARANCE 181
document_text
SP TRAVEL ABROAD JC RELEASED                                                                                                                                                                                                                        18
MONETIZATION 10 DAYS                                                                                                                                                                                                                                16
SP TERMINAL  JC RELEASED                                                                                                                                                                                                                            14
BM TRAVEL ABROAD GENEVIVE RELEASED                                                                                                                                                                                                                  13
GO TRANSITION FOR THE NEW ADMINISTRATION MARK BALLAD RELEASED                                                                                                                                                                                       11
SP TERMINAL  JB RELEASED                                                                                                                                                                                                                             9
REVIEW DETAILS AND MAKE ACTIONS NECESSARY TO COMPLY WITH THE RECOMMENDATION. ATTACHMENT : AOM NO. 2023-006(2025) REVIEW DETAILS AND MAKE ACTIONS NECESSARY TO COMPLY WITH THE RECOMMENDATION. ATTACHMENT : AOM NO. 2023-006(2025) OUT ACCOUNTING     8
VGO TERMINAL  JC RELEASED                                                                                                                                                                                                                            8
SP TRAVEL ABROAD GENEVIVE RELEASED                                                                                                                                                                                                                   8
VICE GOVERNOR TERMINAL  JC RELEASED                                                                                                                                                                                                                  6
PEO RETIREMENT JAYSON RELEASED                                                                                                                                                                                                                       6
PROV'L OFFICE FOR PEOPLE EMPOWERMENT TRAVEL ABROAD (THAILAND) OCTOBER 1 - 4, 2026 SIR MATEO RELEASED                                                                                                                                                 6
GO TERMINAL  MARK BALLAD RELEASED                                                                                                                                                                                                                    5
CHECK TRANSACTION SLIP CHECK TRANSACTION SLIP IN BUREAU OF INTERNAL REVENUE                                                                                                                                                                          4
   RELEASED                                                                                                                                                                                                                                          4
OPA RETIREMENT LOIDA RELEASED                                                                                                                                                                                                                        4
SP TRAVEL ABROAD RONIE RELEASED                                                                                                                                                                                                                      4
BOARD MEMBER TRAVEL ABROAD JOY RELEASED                                                                                                                                                                                                              4
PROVINCIAL NATURAL RESOURCES AND ENVIRONMENTAL OFFICE TERMINAL PAY EFFECTIVE JANUARY 1, 2026) C/O BIANCA RELEASED                                                                                                                                    4
SICK LEAVE  BODY PAIN                                                                                                                                                                                                                                4
Name: count, dtype: int64
COMMUNICATION 52
document_text
SP TRAVEL ABROAD JC RELEASED                                                                                                                                                                                                                        18
MONETIZATION 10 DAYS                                                                                                                                                                                                                                16
SP TERMINAL  JC RELEASED                                                                                                                                                                                                                            14
BM TRAVEL ABROAD GENEVIVE RELEASED                                                                                                                                                                                                                  13
GO TRANSITION FOR THE NEW ADMINISTRATION MARK BALLAD RELEASED                                                                                                                                                                                       11
SP TERMINAL  JB RELEASED                                                                                                                                                                                                                             9
REVIEW DETAILS AND MAKE ACTIONS NECESSARY TO COMPLY WITH THE RECOMMENDATION. ATTACHMENT : AOM NO. 2023-006(2025) REVIEW DETAILS AND MAKE ACTIONS NECESSARY TO COMPLY WITH THE RECOMMENDATION. ATTACHMENT : AOM NO. 2023-006(2025) OUT ACCOUNTING     8
VGO TERMINAL  JC RELEASED                                                                                                                                                                                                                            8
SP TRAVEL ABROAD GENEVIVE RELEASED                                                                                                                                                                                                                   8
VICE GOVERNOR TERMINAL  JC RELEASED                                                                                                                                                                                                                  6
PEO RETIREMENT JAYSON RELEASED                                                                                                                                                                                                                       6
PROV'L OFFICE FOR PEOPLE EMPOWERMENT TRAVEL ABROAD (THAILAND) OCTOBER 1 - 4, 2026 SIR MATEO RELEASED                                                                                                                                                 6
GO TERMINAL  MARK BALLAD RELEASED                                                                                                                                                                                                                    5
CHECK TRANSACTION SLIP CHECK TRANSACTION SLIP IN BUREAU OF INTERNAL REVENUE                                                                                                                                                                          4
   RELEASED                                                                                                                                                                                                                                          4
OPA RETIREMENT LOIDA RELEASED                                                                                                                                                                                                                        4
SP TRAVEL ABROAD RONIE RELEASED                                                                                                                                                                                                                      4
BOARD MEMBER TRAVEL ABROAD JOY RELEASED                                                                                                                                                                                                              4
PROVINCIAL NATURAL RESOURCES AND ENVIRONMENTAL OFFICE TERMINAL PAY EFFECTIVE JANUARY 1, 2026) C/O BIANCA RELEASED                                                                                                                                    4
SICK LEAVE  BODY PAIN                                                                                                                                                                                                                                4
Name: count, dtype: int64
LEAVES 126
document_text
SP TRAVEL ABROAD JC RELEASED                                                                                                                                                                                                                        18
MONETIZATION 10 DAYS                                                                                                                                                                                                                                16
SP TERMINAL  JC RELEASED                                                                                                                                                                                                                            14
BM TRAVEL ABROAD GENEVIVE RELEASED                                                                                                                                                                                                                  13
GO TRANSITION FOR THE NEW ADMINISTRATION MARK BALLAD RELEASED                                                                                                                                                                                       11
SP TERMINAL  JB RELEASED                                                                                                                                                                                                                             9
REVIEW DETAILS AND MAKE ACTIONS NECESSARY TO COMPLY WITH THE RECOMMENDATION. ATTACHMENT : AOM NO. 2023-006(2025) REVIEW DETAILS AND MAKE ACTIONS NECESSARY TO COMPLY WITH THE RECOMMENDATION. ATTACHMENT : AOM NO. 2023-006(2025) OUT ACCOUNTING     8
VGO TERMINAL  JC RELEASED                                                                                                                                                                                                                            8
SP TRAVEL ABROAD GENEVIVE RELEASED                                                                                                                                                                                                                   8
VICE GOVERNOR TERMINAL  JC RELEASED                                                                                                                                                                                                                  6
PEO RETIREMENT JAYSON RELEASED                                                                                                                                                                                                                       6
PROV'L OFFICE FOR PEOPLE EMPOWERMENT TRAVEL ABROAD (THAILAND) OCTOBER 1 - 4, 2026 SIR MATEO RELEASED                                                                                                                                                 6
GO TERMINAL  MARK BALLAD RELEASED                                                                                                                                                                                                                    5
CHECK TRANSACTION SLIP CHECK TRANSACTION SLIP IN BUREAU OF INTERNAL REVENUE                                                                                                                                                                          4
   RELEASED                                                                                                                                                                                                                                          4
OPA RETIREMENT LOIDA RELEASED                                                                                                                                                                                                                        4
SP TRAVEL ABROAD RONIE RELEASED                                                                                                                                                                                                                      4
BOARD MEMBER TRAVEL ABROAD JOY RELEASED                                                                                                                                                                                                              4
PROVINCIAL NATURAL RESOURCES AND ENVIRONMENTAL OFFICE TERMINAL PAY EFFECTIVE JANUARY 1, 2026) C/O BIANCA RELEASED                                                                                                                                    4
SICK LEAVE  BODY PAIN                                                                                                                                                                                                                                4
Name: count, dtype: int64

In [31]:
#Next step: inspect duplicates correctly per class
for label, group in dataset.groupby("label"):
    counts = group["document_text"].value_counts()
    repeated = counts[counts > 1]

    print(f"\n--{label}--")
    print("Repeated unique texts:", len(repeated))
    display(repeated.head(10))
    # display(repeated.head(20))

--AOsMEMOs--
Repeated unique texts: 0

Series([], Name: count, dtype: int64)

--CLEARANCE--
Repeated unique texts: 74

document_text
SP TRAVEL ABROAD JC RELEASED                                                                            18
SP TERMINAL  JC RELEASED                                                                                14
BM TRAVEL ABROAD GENEVIVE RELEASED                                                                      13
GO TRANSITION FOR THE NEW ADMINISTRATION MARK BALLAD RELEASED                                           11
SP TERMINAL  JB RELEASED                                                                                 9
VGO TERMINAL  JC RELEASED                                                                                8
SP TRAVEL ABROAD GENEVIVE RELEASED                                                                       8
VICE GOVERNOR TERMINAL  JC RELEASED                                                                      6
PEO RETIREMENT JAYSON RELEASED                                                                           6
PROV'L OFFICE FOR PEOPLE EMPOWERMENT TRAVEL ABROAD (THAILAND) OCTOBER 1 - 4, 2026 SIR MATEO RELEASED     6
Name: count, dtype: int64

--COMMUNICATION--
Repeated unique texts: 38

document_text
REVIEW DETAILS AND MAKE ACTIONS NECESSARY TO COMPLY WITH THE RECOMMENDATION. ATTACHMENT : AOM NO. 2023-006(2025) REVIEW DETAILS AND MAKE ACTIONS NECESSARY TO COMPLY WITH THE RECOMMENDATION. ATTACHMENT : AOM NO. 2023-006(2025) OUT ACCOUNTING                                                                                                                                                                                                        8
CHECK TRANSACTION SLIP CHECK TRANSACTION SLIP IN BUREAU OF INTERNAL REVENUE                                                                                                                                                                                                                                                                                                                                                                             4
SUBMISSION OF FULL DISCLOSURE POLICY DOCUMENTS SUBMISSION OF FULL DISCLOSURE POLICY DOCUMENTS IN PPDO                                                                                                                                                                                                                                                                                                                                                   3
LIST OF BRGYS WITH NO UNLIQUIDATED FA FROM PGC AS OF MARCH 6, 2025 LIST OF BRGYS WITH NO UNLIQUIDATED FA FROM PGC AS OF MARCH 6, 2025 OUT ACCOUNTING                                                                                                                                                                                                                                                                                                    3
SHF BUDGET ACCOUNTABILITY FORM Nos. 1 and 2 for the 1st Quarter of FY 2025 covering the REPORT OF UTILIZATION AS OF MARCH 31, 2025 SHF BUDGET ACCOUNTABILITY FORM Nos. 1 and 2 for the 1st Quarter of FY 2025 covering the REPORT OF UTILIZATION AS OF MARCH 31, 2025 OUT ACCOUNTING                                                                                                                                                                    3
SUMMARY OF SUPPLIES AND MATERIALS ISSUED (SSMI) report of the PEO-MOTORPOOL Division SUMMARY OF SUPPLIES AND MATERIALS ISSUED (SSMI) report of the PEO-MOTORPOOL Division IN PEO                                                                                                                                                                                                                                                                        3
REQUEST FOR SUBMISSION OF ALL CY 2025 TRANSACTIONS, SUCH AS REPORTS ON THE ISSUANCE AND/OR DISTRIBUTION OF DONATED AND PURCHASED GOODS AND ITEMS FOR STOCK PURPOSES, AND OTHER RELATED TRANSACTIONS FOR ACCOUNTING REQUEST FOR SUBMISSION OF ALL CY 2025 TRANSACTIONS, SUCH AS REPORTS ON THE ISSUANCE AND/OR DISTRIBUTION OF DONATED AND PURCHASED GOODS AND ITEMS FOR STOCK PURPOSES, AND OTHER RELATED TRANSACTIONS FOR ACCOUNTING OUT ACCOUNTING    3
SEND A COPY OF SET OF FINANCIAL STATEMENTS UNDER THE CONSOLIDATED GENERAL FUND, SPECIAL EDUCATION FUND, TRUST FUND, SPECIAL HEALTH FUND AND CONSOLIDATED FUNDS FOR THE YEAR END DECEMBER 31, 2025 SEND A COPY OF SET OF FINANCIAL STATEMENTS UNDER THE CONSOLIDATED GENERAL FUND, SPECIAL EDUCATION FUND, TRUST FUND, SPECIAL HEALTH FUND AND CONSOLIDATED FUNDS FOR THE YEAR END DECEMBER 31, 2025 OUT ACCOUNTING                                      3
REQUEST FOR FINAL INTERVIEW/ COMMENTS ON IPRC FORM REQUEST FOR FINAL INTERVIEW/ COMMENTS ON IPRC FORM IN OFFICE OF THE GOVERNOR                                                                                                                                                                                                                                                                                                                         2
NOTICE OF MEETING PFC MEETING IN PROVINCIAL FINANCE COMMITTEE                                                                                                                                                                                                                                                                                                                                                                                           2
Name: count, dtype: int64

--LEAVES--
Repeated unique texts: 87

document_text
MONETIZATION 10 DAYS                            16
SICK LEAVE  BODY PAIN                            4
COC                                              4
MONETIZATION                                     4
MONETIZATION 15 DAYS                             4
SPECIAL PRIVILEGE  TO ATTEND PERSONAL MATTER     3
SICK LEAVE  HEADACHE                             3
MANDATORY LEAVE                                  3
COMPENSATORY JUNE 26, 2025                       3
MANDATORY AUGUST 01, 2025                        3
Name: count, dtype: int64

In [32]:
label_counts = (
    dataset.groupby("document_text")["label"]
    .nunique()
)

conflicting_texts = label_counts[label_counts > 1]
print("Texts with conflicting labels:", len(conflicting_texts))

Texts with conflicting labels: 0

In [33]:
# Check label conflicts 
from sklearn.model_selection import train_test_split

X = dataset["document_text"]
y = dataset["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20, #means 20% is held aside for testing and 80% is used for training.
    random_state=42, #gives you a reproducible split. Running the notebook again gives you the same train/test allocation.
    stratify=y
)

print("TRAIN")
print(y_train.value_counts())

print("\nTEST:")
print(y_test.value_counts())

TRAIN
label
COMMUNICATION    1828
CLEARANCE         558
LEAVES            523
AOsMEMOs           11
Name: count, dtype: int64

TEST:
label
COMMUNICATION    457
CLEARANCE        140
LEAVES           130
AOsMEMOs           3
Name: count, dtype: int64

In [34]:
#build the baseline text classifier.
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1,2),
    min_df=2
)

X_train_vec = vectorizer.fit_transform(X_train)
x_test_vec = vectorizer.transform(X_test)

print(X_train.shape)
print(x_test_vec.shape)

(2920,)
(730, 9097)

In [35]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000, #means: Logistic Regression doesn't instantly know the best 4 × 9097 weights.
    # An optimizer gradually adjusts them: initial weights -> calculate errors -> adjust coefficients -> calculate errors again -> adjust
    class_weight="balanced"
)

model.fit(X_train_vec, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [36]:

from sklearn.metrics import classification_report

#after training generate predictions
y_pred = model.predict(x_test_vec)

#then evaluate
print(
    #is the evaluation step. It compares: y_test correct answers and y_pred model's answers 
    classification_report( 
        y_test,
        y_pred,
        zero_division=0
    )
)

               precision    recall  f1-score   support

     AOsMEMOs       0.50      0.33      0.40         3
    CLEARANCE       0.99      0.99      0.99       140
COMMUNICATION       1.00      1.00      1.00       457
       LEAVES       0.99      0.99      0.99       130

     accuracy                           0.99       730
    macro avg       0.87      0.83      0.85       730
 weighted avg       0.99      0.99      0.99       730

In [37]:
model.fit(X_train_vec, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [38]:
#do error analysis and leakage checking before trying another model or deep learning.
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred, labels=model.classes_)
print(cm)

[[  1   0   2   0]
 [  0 139   0   1]
 [  1   0 456   0]
 [  0   1   0 129]]

In [39]:
#then inspect the actual mistakes
errors = pd.DataFrame({
    "text": X_test,
    "actual": y_test,
    "predicted": y_pred,
})

display(errors[errors["actual"] !=errors["predicted"]])

,text,actual,predicted
2309,ACCOUNTING SICK LEAVE,CLEARANCE,LEAVES
1755,MEMORANDUM 34A: REQUEST FOR PERMANENT ALTERNAT...,COMMUNICATION,AOsMEMOs
3232,TERMINAL,LEAVES,CLEARANCE
2997,MEMO-2026-41C DIRECTIVE ON MANDATORY COMPLIANC...,AOsMEMOs,COMMUNICATION
2999,MEMO-2026-28 MEMORANDUM ORDER NO. 28 S. 2026 A...,AOsMEMOs,COMMUNICATION

In [40]:
train_texts = set(X_train)
test_texts = set(X_test)

overlap = train_texts.intersection(test_texts)

print("Exact train-test text overlap: ", len(overlap))
#This means you do have leakage risk.

Exact train-test text overlap:  76

In [41]:
#need to split by unique document_text groups, not individual rows.
from sklearn.model_selection import GroupShuffleSplit

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

print(splitter)

GroupShuffleSplit(n_splits=1, random_state=42, test_size=0.2, train_size=None)

In [42]:
X = dataset["document_text"]
y = dataset["label"]
groups = dataset["document_text"]

train_index, test_index = next(
    splitter.split(X, y, groups=groups)
)

X_train = X.iloc[train_index] #X.iloc[train_idx] means: Give me the rows located at these integer positions.
X_test = X.iloc[test_index]

y_train = y.iloc[train_index]
y_test = y.iloc[test_index]

#verify the split 
print("TRAIN:")
print(y_train.value_counts())

print("\nTEST:")
print(y_test.value_counts())

TRAIN:
label
COMMUNICATION    1828
LEAVES            534
CLEARANCE         525
AOsMEMOs           13
Name: count, dtype: int64

TEST:
label
COMMUNICATION    457
CLEARANCE        173
LEAVES           119
AOsMEMOs           1
Name: count, dtype: int64

In [43]:
vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),
    min_df=2
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [44]:
model.fit(X_train_vec, y_train)
y_pred = model.predict(X_test_vec)

In [45]:
print("TRAIN:")
print(y_train.value_counts())

print("\nTEST:")
print(y_test.value_counts())

print(
    "Overlap",
    len(set(X_train).intersection(set(X_test)))
)

TRAIN:
label
COMMUNICATION    1828
LEAVES            534
CLEARANCE         525
AOsMEMOs           13
Name: count, dtype: int64

TEST:
label
COMMUNICATION    457
CLEARANCE        173
LEAVES           119
AOsMEMOs           1
Name: count, dtype: int64
Overlap 0

In [46]:
vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),
    min_df=2
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model.fit(X_train_vec, y_train)
y_pred = model.predict(X_test_vec)

print(classification_report(
    y_test,
    y_pred,
    zero_division=0
))

               precision    recall  f1-score   support

     AOsMEMOs       1.00      1.00      1.00         1
    CLEARANCE       0.99      0.99      0.99       173
COMMUNICATION       0.99      1.00      1.00       457
       LEAVES       0.99      0.97      0.98       119

     accuracy                           0.99       750
    macro avg       0.99      0.99      0.99       750
 weighted avg       0.99      0.99      0.99       750

In [47]:
#this is misclassification analysis or error analysis. actual is the ground-truth label; predicted is the model output.
errors = pd.DataFrame({
    "text":X_test,
    "actual":y_test,
    "predicted":y_pred,
})

errors = errors[errors["actual"] != errors["predicted"]]
display(errors)

print("Total errors:", len(errors))


#then inspect the confusion matrix:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(
    y_test, 
    y_pred,
    labels=model.classes_
)
print(cm)

print(model.classes_)

                                              text     actual      predicted
2317            TUAO DIST HOSP SICK LEAVE MILDRED   CLEARANCE         LEAVES
3002                 VACATION LEAVE  TRAVEL ABROAD     LEAVES      CLEARANCE
3004  SPECIAL PRIVILEGE  TO ATTEND PERSONAL MATTER     LEAVES  COMMUNICATION
3005  SPECIAL PRIVILEGE  TO ATTEND PERSONAL MATTER     LEAVES  COMMUNICATION
3018  SPECIAL PRIVILEGE  TO ATTEND PERSONAL MATTER     LEAVES  COMMUNICATION

Total errors: 5
[[  1   0   0   0]
 [  0 172   0   1]
 [  0   0 457   0]
 [  0   1   3 115]]
['AOsMEMOs' 'CLEARANCE' 'COMMUNICATION' 'LEAVES']

In [48]:
#inspect the learned weights for these terms.
# Data understanding           ✓
# Data cleaning                ✓
# Feature engineering          ✓
# Train/test splitting         ✓
# Baseline training            ✓
# Evaluation                   ✓
# Error analysis               ←
# Data correction
# Retrain baseline
# Compare models
# Cross-validation
# Collect scanned documents
# Deep-learning experiment

terms = ["special", "privilege", "attend", "personal", "matter"]

features = vectorizer.get_feature_names_out()

for term in terms:
    if term in features:
        index = list(features).index(term)
        print(term, dict(zip(model.classes_, model.coef_[:, index])))

special {'AOsMEMOs': np.float64(-0.14609137711904824), 'CLEARANCE': np.float64(-0.3128593801796668), 'COMMUNICATION': np.float64(-0.32596725112659614), 'LEAVES': np.float64(0.7849180084253095)}
privilege {'AOsMEMOs': np.float64(-0.044647569684594574), 'CLEARANCE': np.float64(0.03371257029791875), 'COMMUNICATION': np.float64(-0.37639770247878085), 'LEAVES': np.float64(0.38733270186545554)}
attend {'AOsMEMOs': np.float64(-0.0899237312240259), 'CLEARANCE': np.float64(-0.21852875192397475), 'COMMUNICATION': np.float64(0.1319378389575244), 'LEAVES': np.float64(0.1765146441904767)}
personal {'AOsMEMOs': np.float64(-0.024620019131460235), 'CLEARANCE': np.float64(-0.05190794571389582), 'COMMUNICATION': np.float64(-0.20637960136317435), 'LEAVES': np.float64(0.28290756620853075)}
matter {'AOsMEMOs': np.float64(-0.021706925504813512), 'CLEARANCE': np.float64(-0.04957741582750932), 'COMMUNICATION': np.float64(-0.21614136272820442), 'LEAVES': np.float64(0.287425704060527)}

In [49]:
#inspect the bigrams because your TF-IDF model uses ngram_range=(1, 2).

terms = [
    "special privilege",
    "privilege to",
    "to attend",
    "attend personal",
    "personal matter",
]

matches = leave[
    leave["TYPE OF LEAVE"].str.contains(
        "SPECIAL PRIVILEGE", case=False, na=False
    )
]



for term in terms:
    if term in features:
        index = list(features).index(term)
        print(term, dict(zip(model.classes_, model.coef_[:, index])))


print("\n\n\n")
display(matches)
mask = X_train.str.contains("TO ATTEND", case=False, na=False)

print(y_train[mask].value_counts())
#I've observed about the "to attend" part. i found a mixed signals here
#it favors COMMUNICATION rather than LEAVES.

special privilege {'AOsMEMOs': np.float64(-0.044647569684594574), 'CLEARANCE': np.float64(0.03371257029791875), 'COMMUNICATION': np.float64(-0.37639770247878085), 'LEAVES': np.float64(0.38733270186545554)}
to attend {'AOsMEMOs': np.float64(-0.08096295626877088), 'CLEARANCE': np.float64(-0.15322187908762597), 'COMMUNICATION': np.float64(0.18749107077366536), 'LEAVES': np.float64(0.046693764582731605)}

,DATE FILED,TRANSMITAL DATE,CONTROL#,NAME,TYPE OF LEAVE,REMARKS,DAY/S APPLIED,DATE RECEIVED,STATUS,label,document_text
0,2024-10-28,NaT,2024-10-28-LEAVE-IN-01,"GARMA,JEANNA C.",SPECIAL PRIVILEGE,BIRTHDAY,NaN,2024-10-29,APPROVED,LEAVES,SPECIAL PRIVILEGE BIRTHDAY
3,2024-11-05,NaT,2024-11-05-LEAVE-IN-01,"DELA CRUZ, JOLIE M.",SPECIAL PRIVILEGE,TO ATTEND PERSONAL MATTER,NaN,2024-11-05,APPROVED,LEAVES,SPECIAL PRIVILEGE TO ATTEND PERSONAL MATTER
4,2024-11-12,NaT,2024-11-12-LEAVE-IN-01,"GERVACIO, JENNIFER D.",SPECIAL PRIVILEGE,TO ATTEND PERSONAL MATTER,NaN,2024-11-12,APPROVED,LEAVES,SPECIAL PRIVILEGE TO ATTEND PERSONAL MATTER
15,2024-12-02,NaT,2024-12-02-LEAVE-IN-01,"TAGUINOD, REYNALDO",SPECIAL PRIVILEGE,BIRTHDAY,NaN,2024-12-02,APPROVED,LEAVES,SPECIAL PRIVILEGE BIRTHDAY
17,2024-12-02,NaT,2024-12-02-LEAVE-01,"PEREZ, MELISSA",SPECIAL PRIVILEGE,TO ATTEND PERSONAL MATTER,NaN,2024-12-02,APPROVED,LEAVES,SPECIAL PRIVILEGE TO ATTEND PERSONAL MATTER

label
COMMUNICATION    51
LEAVES            1
Name: count, dtype: int64

In [50]:
sample_text = "SPECIAL PRIVILGE TO ATTEND PERSONAL MATTER"

sample_vec = vectorizer.transform([sample_text])
score = model.decision_function(sample_vec)

print(dict(zip(model.classes_, score[0])))

{'AOsMEMOs': np.float64(-1.6870416850401677), 'CLEARANCE': np.float64(-0.40585584481441844), 'COMMUNICATION': np.float64(1.5031948771540067), 'LEAVES': np.float64(0.5897026527017614)}

In [51]:
#inspect the actual COMMUNICATION examples containing "TO ATTEND":
mask = (
    (y_train == "COMMUNICATION")
    & X_train.str.contains("TO ATTEND", case=False, na=False)
)

display(X_train[mask].head(20))

131     SENDING MS. JENIFER GERVACIO TO ATTEND 3RD MAN...
244     INDORSEMENT LETTER OF MS.DIANA CAFIRMA AND MS....
295     INDORSEMENT MA. JEAL JOSEPHA Q. EDRAIRA TO ATT...
531     INVITATION FOR LOCAL FINANCE COMMITTEE MEMBERS...
562     REQUEST FOR COMMENT AND ACTION ON EMPLOYEES WH...
565     JUSTIFICATION FAILED TO ATTEND STENOGRAPHIC SK...
651     APPROVED REQUEST TO ATTEND TRAINING/WORKSHOP/C...
760     ATTN TO ACCTNG FROM PA TO ATTEND THE COA GUIDE...
810     REQUEST TO ALLOW THE FF BOD AND COMMITTEE TO A...
828     INVITATION FROM CENTER FOR GLOBAL BEST PRACTIC...
844     TRAINING REQUEST OF MS. MARICAR LARDIZABAL AND...
854     INVITING GOV MAMBA AS THEIR GUEST OF HONOR AND...
978     TRAVEL ORDER to MS. MELISSA L. PEREZ TO ATTEND...
1000    YELLOW CLUSTER MEETING: AUGUST 12, 2025 9:00AM...
1087    ATTENDANCE TO ORIENTATION ON THE EGOVph APP ; ...
1188    MEMORANDUM ORDER NO. 89, S.2025 INVITATION TO ...
1218    INVITATION TO ATTEND 3RD QUARTERLY CONFERENCE ...
1280    APPROVED BY GOV: INVITATION TO ATTEND 3RD QUAR...
1450    INVITATION TO ATTEND THE PROVINCIAL SK FEDERAT...
1468    MEMORANDUM ORDER NO. 02, S. 2026: INVITATION T...
Name: document_text, dtype: str

In [52]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(
    class_weight="balanced"
)

svm_model.fit(X_train_vec, y_train)
svm_pred = svm_model.predict(X_test_vec)

#evaluate
print(classification_report(
    y_test,
    svm_pred,
    zero_division=0
))

#precision - when the model says this class, can I trust it?
#recall - of all the real documents in this class, how many did i find?
#f1-score - balancing the precision and recall
#support - how many actual examples were tested

               precision    recall  f1-score   support

     AOsMEMOs       0.00      0.00      0.00         1
    CLEARANCE       0.99      0.99      0.99       173
COMMUNICATION       1.00      1.00      1.00       457
       LEAVES       0.99      0.99      0.99       119

     accuracy                           1.00       750
    macro avg       0.75      0.75      0.75       750
 weighted avg       0.99      1.00      1.00       750

In [53]:
#model benchmarking.
lr_cv_pred = model.predict(X_test_vec)
svm_pred = svm_model.predict(X_test_vec)

from sklearn.metrics import classification_report

lr_report = classification_report(
    y_test, lr_cv_pred, zero_division=0, output_dict=True
)

svm_report = classification_report(
    y_test, svm_pred, zero_division=0, output_dict=True
)

output_dict=True

print("Logistic Regression")
print("Accuracy:", lr_report["accuracy"])
print("Macro F1:", lr_report["macro avg"]["f1-score"])

print("\nLinear SVM")
print("Accuracy:", svm_report["accuracy"])
print("Macro F1:", svm_report["macro avg"]["f1-score"])

Logistic Regression
Accuracy: 0.9933333333333333
Macro F1: 0.9924178799529567

Linear SVM
Accuracy: 0.996
Macro F1: 0.7461808489149474

In [54]:
for label in model.classes_:
    print(
        label,
        "LR:", lr_report[label]["f1-score"],
        "SVM:", svm_report[label]["f1-score"]
    )
    #LR - Logistic regression
    #SVM- Linear Support Vector Machine

    print("\n")

#Compare individual classes 
for label in model.classes_:
    print(
        label,
        "LR:", lr_report[label]["f1-score"],
        "SVM:", svm_report[label]["f1-score"]
    )

AOsMEMOs LR: 1.0 SVM: 0.0


CLEARANCE LR: 0.9942196531791907 SVM: 0.9942196531791907


COMMUNICATION LR: 0.9967284623773174 SVM: 0.9989071038251366


LEAVES LR: 0.9787234042553191 SVM: 0.9915966386554622


AOsMEMOs LR: 1.0 SVM: 0.0
CLEARANCE LR: 0.9942196531791907 SVM: 0.9942196531791907
COMMUNICATION LR: 0.9967284623773174 SVM: 0.9989071038251366
LEAVES LR: 0.9787234042553191 SVM: 0.9915966386554622

In [55]:
#STRATIFIED GROUP K-FOLD CROSS-VALIDATION 
from sklearn.model_selection import StratifiedGroupKFold

cv = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

groups = dataset["document_text"]

#inspect the folds before training anything
#why 5 folds - enough repetitions for a better performance estimate and not too computationally expensive
for fold, (train_idx, test_idx) in enumerate(
    cv.split(dataset["document_text"], dataset["label"], groups)
):
    print(f"\nFold {fold + 1}")
    print("TRAIN:")
    print(dataset.iloc[train_idx]["label"].value_counts())
    print("TEST:")
    print(dataset.iloc[test_idx]["label"].value_counts())

Fold 1
TRAIN:
label
COMMUNICATION    1828
CLEARANCE         558
LEAVES            523
AOsMEMOs           11
Name: count, dtype: int64
TEST:
label
COMMUNICATION    457
CLEARANCE        140
LEAVES           130
AOsMEMOs           3
Name: count, dtype: int64

Fold 2
TRAIN:
label
COMMUNICATION    1828
CLEARANCE         558
LEAVES            522
AOsMEMOs           11
Name: count, dtype: int64
TEST:
label
COMMUNICATION    457
CLEARANCE        140
LEAVES           131
AOsMEMOs           3
Name: count, dtype: int64

Fold 3
TRAIN:
label
COMMUNICATION    1828
CLEARANCE         559
LEAVES            522
AOsMEMOs           11
Name: count, dtype: int64
TEST:
label
COMMUNICATION    457
CLEARANCE        139
LEAVES           131
AOsMEMOs           3
Name: count, dtype: int64

Fold 4
TRAIN:
label
COMMUNICATION    1828
CLEARANCE         559
LEAVES            522
AOsMEMOs           11
Name: count, dtype: int64
TEST:
label
COMMUNICATION    457
CLEARANCE        139
LEAVES           131
AOsMEMOs           3
Name: count, dtype: int64

Fold 5
TRAIN:
label
COMMUNICATION    1828
CLEARANCE         558
LEAVES            523
AOsMEMOs           12
Name: count, dtype: int64
TEST:
label
COMMUNICATION    457
CLEARANCE        140
LEAVES           130
AOsMEMOs           2
Name: count, dtype: int64

In [56]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_validate

lr_pipeline = Pipeline([ #Pipeline is an ML pipeline. It chains preprocessing and modelling together
    ("tfidf", TfidfVectorizer(
        lowercase=True, ngram_range=(1,2), min_df=2
    )),
    ("model", LogisticRegression(
        max_iter=1000, class_weight="balanced"
    ))
])

#evaluate
scores = cross_validate(
    lr_pipeline,
    dataset["document_text"],
    dataset["label"],
    groups=groups,
    cv=cv,
    scoring=["accuracy", "f1_macro"]
)

print("Accuracy:", scores["test_accuracy"])
print("Macro F1:", scores["test_f1_macro"])

print("Mean Accuracy:", scores["test_accuracy"].mean())
print("Mean Macro F1:", scores["test_f1_macro"].mean())

Accuracy: [0.98767123 0.98905609 0.99315068 0.9890411  0.99725652]
Macro F1: [0.82477541 0.8671859  0.84671378 0.84236697 0.91522476]
Mean Accuracy: 0.9912351234049928
Mean Macro F1: 0.8592533637625837

In [57]:
#5-fold Stratified Group K-Fold cross-validation for Linear SVM
#so we can compare it fairly against logistic regression

svm_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True, ngram_range=(1, 2), min_df=2
    )),
    ("model", LinearSVC(
        class_weight="balanced"
    ))
])

svm_scores = cross_validate(
    svm_pipeline,
    dataset["document_text"],
    dataset["label"],
    groups=groups,
    cv=cv,
    scoring=["accuracy", "f1_macro"]
)


#inspect
print("Accuracy:", svm_scores["test_accuracy"])
print("Macro F1:", svm_scores["test_f1_macro"])
print("Mean Accuracy:", svm_scores["test_accuracy"].mean())
print("Mean Macro F1:", svm_scores["test_f1_macro"].mean())

Accuracy: [0.99315068 0.99179207 0.99315068 0.9890411  0.99862826]
Macro F1: [0.84547154 0.909402   0.74671675 0.84236697 0.99883072]
Mean Accuracy: 0.9931525578608833
Mean Macro F1: 0.8685575962687494

In [58]:
#use cross_val_predict() so every row receives a predictions from a model that did not train on that row
from sklearn.model_selection import cross_val_predict

svm_cv_pred=cross_val_predict(
    svm_pipeline,
    dataset["document_text"],
    dataset["label"],
    groups=groups,
    cv=cv,
)

print(classification_report(
    dataset["label"] ,
    svm_cv_pred,
    zero_division=0
))

               precision    recall  f1-score   support

     AOsMEMOs       0.67      0.43      0.52        14
    CLEARANCE       1.00      0.99      0.99       698
COMMUNICATION       0.99      1.00      1.00      2285
       LEAVES       1.00      0.99      0.99       653

     accuracy                           0.99      3650
    macro avg       0.91      0.85      0.88      3650
 weighted avg       0.99      0.99      0.99      3650

In [59]:
#use same pipeline at the top. with the same cv and groups 
from sklearn.model_selection import cross_val_predict

lr_cv_pred=cross_val_predict(
    lr_pipeline,
    dataset["document_text"],
    dataset["label"],
    groups=groups,
    cv=cv,
)

print(classification_report(
    dataset["label"] ,
    lr_cv_pred,
    zero_division=0
))

               precision    recall  f1-score   support

     AOsMEMOs       0.46      0.43      0.44        14
    CLEARANCE       1.00      0.99      0.99       698
COMMUNICATION       0.99      1.00      0.99      2285
       LEAVES       1.00      0.98      0.99       653

     accuracy                           0.99      3650
    macro avg       0.86      0.85      0.86      3650
 weighted avg       0.99      0.99      0.99      3650

In [60]:
#rows = actual class
#columns = predicted class
from sklearn.metrics import confusion_matrix

classes = sorted(dataset["label"].unique())

cm = confusion_matrix(
    dataset["label"],
    lr_cv_pred,
    labels=classes
)

print(classes)
print(cm)

['AOsMEMOs', 'CLEARANCE', 'COMMUNICATION', 'LEAVES']
[[   6    0    8    0]
 [   0  693    2    3]
 [   7    0 2278    0]
 [   0    3    9  641]]

In [61]:
#Isolate them like this 
cv_results = dataset.copy()
cv_results["predicted"] = lr_cv_pred

errors = cv_results[
    cv_results["label"] != cv_results["predicted"]
]

display(
    errors[
        (errors["label"] == "AOsMEMOs") &
        (errors["predicted"] == "COMMUNICATION")
    ]
)

reverse_errors = errors[
    (errors["label"] == "COMMUNICATION")
    & (errors["predicted"] == "AOsMEMOs")
]

display(reverse_errors[["document_text", "label", "predicted"]])

,document_text,label,predicted
2989,AO-2026-1A APPROVING AND ADOPTING THE JOINT RE...,AOsMEMOs,COMMUNICATION
2991,EO-2026-06 RECONSTITUTING THE COMPREHENSIVE DE...,AOsMEMOs,COMMUNICATION
2995,MEMO-2026-34A MEMORANDUM 34A: REQUEST FOR PERM...,AOsMEMOs,COMMUNICATION
2996,MEMO-2026-04-13-01 DOCUMENTARY REQUIREMENTS FO...,AOsMEMOs,COMMUNICATION
2997,MEMO-2026-41C DIRECTIVE ON MANDATORY COMPLIANC...,AOsMEMOs,COMMUNICATION
2998,MEMO-2026-41 REITERATE THE SUBMISSION OF THE P...,AOsMEMOs,COMMUNICATION
2999,MEMO-2026-28 MEMORANDUM ORDER NO. 28 S. 2026 A...,AOsMEMOs,COMMUNICATION
3000,AO-2026-13 REORGANIZING THE ADMINISTRATIVE AND...,AOsMEMOs,COMMUNICATION

,document_text,label,predicted
1527,AO NO. 02 S. 2026 - ORDER ADOPTING THE GUIDELI...,COMMUNICATION,AOsMEMOs
1696,EXCUTIVE ORDER NO. 11 S. 2026 RE AN EXECUTIVE ...,COMMUNICATION,AOsMEMOs
1713,ADMINISTRATIVE ORDER NO. 10 S. 2026 RE AN ORDE...,COMMUNICATION,AOsMEMOs
1755,MEMORANDUM 34A: REQUEST FOR PERMANENT ALTERNAT...,COMMUNICATION,AOsMEMOs
1802,"MEMORANDUM ORDER NO. 41-C, S. 2026: DIRECTIVE ...",COMMUNICATION,AOsMEMOs
1849,MEMORANDUM ORDER NO. 28 S. 2026 ADOPTION OF LA...,COMMUNICATION,AOsMEMOs
1884,AO NO. 13: REORGANIZING THE ADMINISTRATIVE AND...,COMMUNICATION,AOsMEMOs

In [62]:
normalized = (
    dataset["document_text"]
    .str.upper()
    .str.replace(r"[^A-Z0-9\s]", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

dataset["normalized_text"] = normalized

conflicts = (
    dataset.groupby("normalized_text")["label"]
    .nunique()
)

print("Normalized conflicts:", (conflicts > 1).sum())

Normalized conflicts: 0

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vec = TfidfVectorizer(ngram_range=(1, 2))
X_sim = vec.fit_transform(dataset["normalized_text"])

similarity = cosine_similarity(X_sim)

# print(similarity, vec, X_sim)
# display(vec, X_sim, similarity)

In [64]:
threshold = 0.90
pairs = []

for i in range(len(dataset)):
    for j in range(i + 1, len(dataset)):
        if dataset.iloc[i]["label"] != dataset.iloc[j]["label"]:
            if similarity[i, j] >= threshold:
                pairs.append((i, j, similarity[i, j]))

                print("Cross-class near-duplicates:", len(pairs))
                print(pairs[:10])

Cross-class near-duplicates: 1
[(1849, 2995, np.float64(0.9194137370236222))]

In [66]:
i, j, score = pairs[0]

print("Similarity:", score)
print("\nDocument A:")
print(dataset.iloc[i][["label", "document_text"]])

print("\nDocument B:")
print(dataset.iloc[j][["label", "document_text"]])

Similarity: 0.9194137370236222

Document A:
label                                                COMMUNICATION
document_text    MEMORANDUM ORDER NO. 28 S. 2026 ADOPTION OF LA...
Name: 1849, dtype: str

Document B:
label                                                     AOsMEMOs
document_text    MEMO-2026-28 MEMORANDUM ORDER NO. 28 S. 2026 A...
Name: 2999, dtype: str

In [67]:
mask = dataset["document_text"].str.contains(
    r"\b(ADMINISTRATIVE ORDER|EXECUTIVE ORDER|MEMORANDUM ORDER|MEMORANDUM)\b",
    case=False,
    regex=True,
    na=False,
)

review = dataset[(dataset["label"] == "COMMUNICATION") & mask]
display(review[["document_text", "label"]])

C:\Users\ASUS\AppData\Local\Temp\ipykernel_25148\649226844.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = dataset["document_text"].str.contains(

                                          document_text          label
27    MEMORANDUM ORDER NO. 03,2024 IMPLEMENTATION OF...  COMMUNICATION
190   INTERNAL AUDIT MEMORANDUM NO. 01S, 2024 REITER...  COMMUNICATION
211   MEMORANDUM OF AGREEMENT IMPLEMENTATION OF HEAL...  COMMUNICATION
233   PROPOSED DRAFT TRIPARTITE MEMORANDUM OF AGREEM...  COMMUNICATION
312   MEMORANDUM TO MR. JULIUS G. CALIMARAN DIESIGNA...  COMMUNICATION
...                                                 ...            ...
2251  MEMORANDUM NO. 87-A-2026: ATTENDANCE ON THE CO...  COMMUNICATION
2256  MEMORANDUM NO. 85-D: ATTENDANCE TO CAPACITY BU...  COMMUNICATION
2262  REPLY TO LETTER RE: MEMORANDUM DATED FEB. 20, ...  COMMUNICATION
2263  LETTER TO HON. EDGAR B. AGLIPAY RE COPY OF THE...  COMMUNICATION
2267  MEMORANDUM NO. 89-2026: ATTENDANCE TO THE COND...  COMMUNICATION

[182 rows x 2 columns]

In [69]:
mask = dataset["document_text"].str.contains(
    r"\b(AO\b|EO\b|ADMINISTRATIVE ORDER|EXECUTIVE ORDER|MEMORANDUM|MEMO\b)",
    case=False,
    regex=True,
    na=False,
)

review = dataset[
    (dataset["label"] == "COMMUNICATION") & mask
]

display(review[["document_text", "label"]])

C:\Users\ASUS\AppData\Local\Temp\ipykernel_25148\382457867.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = dataset["document_text"].str.contains(

                                          document_text          label
27    MEMORANDUM ORDER NO. 03,2024 IMPLEMENTATION OF...  COMMUNICATION
190   INTERNAL AUDIT MEMORANDUM NO. 01S, 2024 REITER...  COMMUNICATION
211   MEMORANDUM OF AGREEMENT IMPLEMENTATION OF HEAL...  COMMUNICATION
233   PROPOSED DRAFT TRIPARTITE MEMORANDUM OF AGREEM...  COMMUNICATION
312   MEMORANDUM TO MR. JULIUS G. CALIMARAN DIESIGNA...  COMMUNICATION
...                                                 ...            ...
2256  MEMORANDUM NO. 85-D: ATTENDANCE TO CAPACITY BU...  COMMUNICATION
2262  REPLY TO LETTER RE: MEMORANDUM DATED FEB. 20, ...  COMMUNICATION
2263  LETTER TO HON. EDGAR B. AGLIPAY RE COPY OF THE...  COMMUNICATION
2265  EO 35 S. 2026 ; CREATING THE PROVINCIAL IMMUNI...  COMMUNICATION
2267  MEMORANDUM NO. 89-2026: ATTENDANCE TO THE COND...  COMMUNICATION

[219 rows x 2 columns]

In [71]:
strong_pattern = (
    r"\b(ADMINISTRATIVE ORDER|EXECUTIVE ORDER|"
    r"MEMORANDUM ORDER|MEMORANDUM NO\.?|"
    r"AO NO\.?|EO NO\.?)\b"
)

strong_review = review[
    review["document_text"].str.contains(
        strong_pattern, case=False, regex=True, na=False
    )
]


print("Strong candidates:", len(strong_review))
display(strong_review[["document_text", "label"]])

Strong candidates: 149

C:\Users\ASUS\AppData\Local\Temp\ipykernel_25148\2525516536.py:8: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  review["document_text"].str.contains(

                                          document_text          label
27    MEMORANDUM ORDER NO. 03,2024 IMPLEMENTATION OF...  COMMUNICATION
190   INTERNAL AUDIT MEMORANDUM NO. 01S, 2024 REITER...  COMMUNICATION
321   MEMORANDUM ORDER DATED NOVEMBER 13,2024 APPROV...  COMMUNICATION
438   EXECUTIVE ORDER NO. 1, SERIES OF 2025,"AN ORDI...  COMMUNICATION
467   DOST AO NO. 011, SERIES OF 2020 RE: REVISED  G...  COMMUNICATION
...                                                 ...            ...
2179  MEMORANDUM ORDER NO. 036, 2026:SUBMISSION OF D...  COMMUNICATION
2240  MEMORANDUM ORDER RE: REGISTRATION FOR THE PHIL...  COMMUNICATION
2251  MEMORANDUM NO. 87-A-2026: ATTENDANCE ON THE CO...  COMMUNICATION
2256  MEMORANDUM NO. 85-D: ATTENDANCE TO CAPACITY BU...  COMMUNICATION
2267  MEMORANDUM NO. 89-2026: ATTENDANCE TO THE COND...  COMMUNICATION

[149 rows x 2 columns]

In [74]:
review_df = strong_review.copy()

review_df["original_label"] = review_df["label"]
review_df["reviewed_label"] = ""
review_df["review_status"] = "pending"

display(
    review_df[
        ["document_text", "original_label",
         "reviewed_label", "review_status"]
    ].head(30)
)

,document_text,original_label,reviewed_label,review_status
27,"MEMORANDUM ORDER NO. 03,2024 IMPLEMENTATION OF...",COMMUNICATION,,pending
190,"INTERNAL AUDIT MEMORANDUM NO. 01S, 2024 REITER...",COMMUNICATION,,pending
321,"MEMORANDUM ORDER DATED NOVEMBER 13,2024 APPROV...",COMMUNICATION,,pending
438,"EXECUTIVE ORDER NO. 1, SERIES OF 2025,""AN ORDI...",COMMUNICATION,,pending
467,"DOST AO NO. 011, SERIES OF 2020 RE: REVISED G...",COMMUNICATION,,pending
657,FAMILIARIZATION SESSION ON THE PROPER COMPLETI...,COMMUNICATION,,pending
686,DEPARTMENT MEMORANDUM No. 2024-0462: ADVISORY ...,COMMUNICATION,,pending
772,"INTERNAL AUDIT MEMORANDUM ORDER NO.08, S.2025...",COMMUNICATION,,pending
795,"EXECUTIVE ORDER NO. 05-A, s. 2025: AN ORDER CR...",COMMUNICATION,,pending
851,"ADMINISTRATIVE ORDER NO. 04, SERIES OF 2025: A...",COMMUNICATION,,pending
852,"MEMORANDUM ORDER NO. 59, 2025 442ND AGGAO NAC ...",COMMUNICATION,,pending
853,"MEMORANDUM ORDER NO. 43, s. 2025: SUBMISSION O...",COMMUNICATION,,pending
859,"MEMORANDUM ORDER NO. 62, 2025: 442ND AGGAO NA...",COMMUNICATION,,pending
873,"MEMORANDUM ORDER NO. 66 S, 2025 BEST ROCKISTA ...",COMMUNICATION,,pending
876,"MEMORANDUM ORDER NO. 59-A, S. 2025: SUBMISSION...",COMMUNICATION,,pending
882,"MEMORANDUM ORDER NO.65, S.2025: ALL MEMBERS OF...",COMMUNICATION,,pending
898,ADMINISTRATIVE ORDER NO. 5 S. 2025 - AN ORDER ...,COMMUNICATION,,pending
978,TRAVEL ORDER to MS. MELISSA L. PEREZ TO ATTEND...,COMMUNICATION,,pending
996,"MEMORANDUM ORDER NO.77 S, 2025 STANDARD PROGAR...",COMMUNICATION,,pending
1005,"MEMORANDUM ORDER NO.78, S.2025 RULES ON DESIGN...",COMMUNICATION,,pending
1008,MEMORANDUM NO. 013 S. 2025 PRIORITIZATION OF S...,COMMUNICATION,,pending
1009,MEMORANDUM NO. 012 S. 2025 CREATION OF SGLG TE...,COMMUNICATION,,pending
1057,"EXECUTIVE ORDERS NO. 2, 3, 4, S. 2025 EO NO. 2...",COMMUNICATION,,pending
1107,MEMORANDUM ORDER NO. 020 AS PER THE GOVERNORS ...,COMMUNICATION,,pending
1120,"MEMORANDUM ORDER NO. 37, S.2025 SUSPENSION OF ...",COMMUNICATION,,pending
1124,"MEMORANDUM ORDER NO. 023, S.2025 ENDORSEMENET ...",COMMUNICATION,,pending
1125,"MEMORANDUM NO. 280, S.2025 ENDORSEMENT OF REPO...",COMMUNICATION,,pending
1135,"ADMINISTRATIVE ORDER NO. 02, S.2025 AN ORDER C...",COMMUNICATION,,pending
1138,"MEMORANDUM NO. 41, S.2025\nTO: Mr. OLIVER B. P...",COMMUNICATION,,pending
1139,"MEMORANDUM NO. 86, S.2025: SUB-CAPITOL MANPOWE...",COMMUNICATION,,pending

In [84]:
review_df.loc[795, "reviewed_label"] = "AOsMEMOs"
review_df.loc[795, "review_status"] = "verified"

review_df.loc[978, "reviewed_label"] = "COMMUNICATION"
review_df.loc[978, "review_status"] = "verified"

review_df.loc[467, "review_status"] = "needs_domain_review"

print(review_df["review_status"].value_counts())

display(
    review_df[review_df["review_status"] == "verified"][
        ["document_text", "original_label", "reviewed_label"]
    ]
)

review_status
pending                144
verified                 4
needs_domain_review      1
Name: count, dtype: int64

,document_text,original_label,reviewed_label
438,"EXECUTIVE ORDER NO. 1, SERIES OF 2025,""AN ORDI...",COMMUNICATION,AOsMEMOs
795,"EXECUTIVE ORDER NO. 05-A, s. 2025: AN ORDER CR...",COMMUNICATION,AOsMEMOs
851,"ADMINISTRATIVE ORDER NO. 04, SERIES OF 2025: A...",COMMUNICATION,AOsMEMOs
978,TRAVEL ORDER to MS. MELISSA L. PEREZ TO ATTEND...,COMMUNICATION,COMMUNICATION

In [85]:
pending = review_df[
    review_df["review_status"] == "pending"
]

display(
    pending[
        ["document_text", "original_label"]
    ].head(20)
)

                                          document_text original_label
27    MEMORANDUM ORDER NO. 03,2024 IMPLEMENTATION OF...  COMMUNICATION
190   INTERNAL AUDIT MEMORANDUM NO. 01S, 2024 REITER...  COMMUNICATION
321   MEMORANDUM ORDER DATED NOVEMBER 13,2024 APPROV...  COMMUNICATION
657   FAMILIARIZATION SESSION ON THE PROPER COMPLETI...  COMMUNICATION
686   DEPARTMENT MEMORANDUM No. 2024-0462: ADVISORY ...  COMMUNICATION
772   INTERNAL AUDIT  MEMORANDUM ORDER NO.08, S.2025...  COMMUNICATION
852   MEMORANDUM ORDER NO. 59, 2025 442ND AGGAO NAC ...  COMMUNICATION
853   MEMORANDUM ORDER NO. 43, s. 2025: SUBMISSION O...  COMMUNICATION
859   MEMORANDUM ORDER NO. 62, 2025:  442ND AGGAO NA...  COMMUNICATION
873   MEMORANDUM ORDER NO. 66 S, 2025 BEST ROCKISTA ...  COMMUNICATION
876   MEMORANDUM ORDER NO. 59-A, S. 2025: SUBMISSION...  COMMUNICATION
882   MEMORANDUM ORDER NO.65, S.2025: ALL MEMBERS OF...  COMMUNICATION
898   ADMINISTRATIVE ORDER NO. 5 S. 2025 - AN ORDER ...  COMMUNICATION
996   MEMORANDUM ORDER NO.77 S, 2025 STANDARD PROGAR...  COMMUNICATION
1005  MEMORANDUM ORDER NO.78, S.2025 RULES ON DESIGN...  COMMUNICATION
1008  MEMORANDUM NO. 013 S. 2025 PRIORITIZATION OF S...  COMMUNICATION
1009  MEMORANDUM NO. 012 S. 2025 CREATION OF SGLG TE...  COMMUNICATION
1057  EXECUTIVE ORDERS NO. 2, 3, 4, S. 2025 EO NO. 2...  COMMUNICATION
1107  MEMORANDUM ORDER NO. 020 AS PER THE GOVERNORS ...  COMMUNICATION
1120  MEMORANDUM ORDER NO. 37, S.2025 SUSPENSION OF ...  COMMUNICATION

In [86]:
aomemo_ids = [27, 190, 321, 772, 852, 853, 859, 873]

review_df.loc[aomemo_ids, "reviewed_label"] = "AOsMEMOs"
review_df.loc[aomemo_ids, "review_status"] = "verified"